### PR TITLE
Confirm Account Feature

### PR DESCRIPTION
**Pull request by eyeamkd**
Confirm Account Feature :
- Single Sign in for Admin and Users 
- Routes changes as per Admin/User 
- Toggling Menu Icon as per Admin/User 
- Admin Dashboard shows user information 
- Admin able to verify/reject users from dashboard 
- Users who aren't verified will not be able to add new post nor add new D-Space 
- Post Approval the New Post and New D-Space Components are visible clearly 
- Added Blurry Effect for rich UX 
- Made the Drawer width dynamic 
- Removed Drawer for Admin 

post merging this PR adds #51 into DISHA

### CODE REVIEW

**Comment by akylus** [comment]
image

**Comment by akylus** [comment]
image

**Comment by akylus** [comment]
feeling lazy, hence the SSs. Fix them & lemme know

**Comment by eyeamkd** [comment]
> feeling lazy, hence the SSs. Fix them & lemme know

@akylus   fixed the routing issue, and the styles are applied on hot reload check and lemme know the changes, if any

**Comment by akylus** [comment]
oofest moment.
admin account now visible without even logging in LMAO
image

Here's an SS confirmation from mobile (same from mobile's incognito)
image

**Comment by akylus** [comment]
image

### Styling still messing up

Repro:

### 1. go to "/" endpoint while signed in
2. hit signout

**Comment by akylus** [comment]
@eyeamkd

**Comment by eyeamkd** [comment]
LOL 😂😂😂😂😂😂

**Comment by eyeamkd** [comment]
@akylus modified check for the routes, test it out and lemme know

**Pull request merged**
