### PR TITLE
Comments Feature 🍾

### LINKED ISSUE #83: Comments Feature for Posts

### PR DESCRIPTION
**Pull request by eyeamkd**
Implemented Basic Comments Feature  
- Able to place a comment on any post 
- Able to go to user profile who placed a comment on username click
- Able to see the date when the comment was posted

Features that I felt could be added in future 
- Time in hours when the comment was added 
- Reply to a comment 
- Like a comment  

Hopefully this closes #83

### CODE REVIEW

**Comment by akylus** [comment]
Comments not working. Please check.

**Comment by akylus** [comment]
still not working.. pls checC

**Comment by eyeamkd** [comment]
> still not working.. pls checC

Check now, if doesn't work I'm gonna leave github

**Comment by akylus** [comment]
image

Post stuck on loading when opened in Incognito.
(I hope you're ready with an alternative for GitHub.)

**Comment by akylus** [comment]
@eyeamkd also, I have added some code fixing smol bugs.. pull before you push

**Comment by akylus** [comment]
> > still not working.. pls checC
> 
> @akylus Check now, if doesn't work I'm gonna leave github

sTiLL n0t worKinG pLss chexcc

**Comment by eyeamkd** [comment]
> image
> 
> Post stuck on loading when opened in Incognito.
> (I hope you're ready with an alternative for GitHub.)
> 
> 
> 

# Was happening before too, remember?
Does it have anything to do with comments? 😰

**Comment by eyeamkd** [comment]
> good job br0

Rulayega kya pagle

**Pull request merged**
